org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.parallel.tasks.in.project=true

# KSP
ksp.incremental=true
ksp.incremental.log=true
ksp.use.k2=false

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false
